version: '2'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: bitnami/cassandra:latest
    volumes:
      - ./.data/cassandra:/bitnami
    ports:
      - 9042:9042

    networks:
      - app-tier
  centrifugo:
    image: centrifugo/centrifugo
    ports:
      - 8001:8000
    networks:
      - app-tier
    volumes:
      - ./.config/centrifugo:/centrifugo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis-master:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    networks:
      - app-tier