server_port: 0.0.0.0:9000
db_host: localhost
db_port: 9042
db_username: cassandra
db_password: cassandra
db_keyspace: blachat1
redis_host: localhost
redis_port: 6379
service_sceret: redbulll
http_key: 123456
http_secret: 123455
centrifugo_url: http://localhost:8001
centrifugo_key: key