// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MethodType int32

const (
	MethodType_PUBLISH        MethodType = 0
	MethodType_BROADCAST      MethodType = 1
	MethodType_UNSUBSCRIBE    MethodType = 2
	MethodType_DISCONNECT     MethodType = 3
	MethodType_PRESENCE       MethodType = 4
	MethodType_PRESENCE_STATS MethodType = 5
	MethodType_HISTORY        MethodType = 6
	MethodType_HISTORY_REMOVE MethodType = 7
	MethodType_CHANNELS       MethodType = 8
	MethodType_INFO           MethodType = 9
)

var MethodType_name = map[int32]string{
	0: "PUBLISH",
	1: "BROADCAST",
	2: "UNSUBSCRIBE",
	3: "DISCONNECT",
	4: "PRESENCE",
	5: "PRESENCE_STATS",
	6: "HISTORY",
	7: "HISTORY_REMOVE",
	8: "CHANNELS",
	9: "INFO",
}

var MethodType_value = map[string]int32{
	"PUBLISH":        0,
	"BROADCAST":      1,
	"UNSUBSCRIBE":    2,
	"DISCONNECT":     3,
	"PRESENCE":       4,
	"PRESENCE_STATS": 5,
	"HISTORY":        6,
	"HISTORY_REMOVE": 7,
	"CHANNELS":       8,
	"INFO":           9,
}

func (x MethodType) String() string {
	return proto.EnumName(MethodType_name, int32(x))
}

func (MethodType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type ClientInfo struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Client               string   `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	ConnInfo             []byte   `protobuf:"bytes,3,opt,name=conn_info,json=connInfo,proto3" json:"conn_info,omitempty"`
	ChanInfo             []byte   `protobuf:"bytes,4,opt,name=chan_info,json=chanInfo,proto3" json:"chan_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ClientInfo) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *ClientInfo) GetConnInfo() []byte {
	if m != nil {
		return m.ConnInfo
	}
	return nil
}

func (m *ClientInfo) GetChanInfo() []byte {
	if m != nil {
		return m.ChanInfo
	}
	return nil
}

type Publication struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Info                 *ClientInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Publication) Reset()         { *m = Publication{} }
func (m *Publication) String() string { return proto.CompactTextString(m) }
func (*Publication) ProtoMessage()    {}
func (*Publication) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Publication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publication.Unmarshal(m, b)
}
func (m *Publication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publication.Marshal(b, m, deterministic)
}
func (m *Publication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publication.Merge(m, src)
}
func (m *Publication) XXX_Size() int {
	return xxx_messageInfo_Publication.Size(m)
}
func (m *Publication) XXX_DiscardUnknown() {
	xxx_messageInfo_Publication.DiscardUnknown(m)
}

var xxx_messageInfo_Publication proto.InternalMessageInfo

func (m *Publication) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Publication) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Publication) GetInfo() *ClientInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Command struct {
	Id                   uint32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method               MethodType `protobuf:"varint,2,opt,name=method,proto3,enum=api.MethodType" json:"method,omitempty"`
	Params               []byte     `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Command) GetMethod() MethodType {
	if m != nil {
		return m.Method
	}
	return MethodType_PUBLISH
}

func (m *Command) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type Reply struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result               []byte   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Reply) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type PublishRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PublishRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PublishResponse struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *PublishResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PublishResponse) GetResult() *PublishResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type PublishResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResult) Reset()         { *m = PublishResult{} }
func (m *PublishResult) String() string { return proto.CompactTextString(m) }
func (*PublishResult) ProtoMessage()    {}
func (*PublishResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *PublishResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResult.Unmarshal(m, b)
}
func (m *PublishResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResult.Marshal(b, m, deterministic)
}
func (m *PublishResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResult.Merge(m, src)
}
func (m *PublishResult) XXX_Size() int {
	return xxx_messageInfo_PublishResult.Size(m)
}
func (m *PublishResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResult.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResult proto.InternalMessageInfo

type BroadcastRequest struct {
	Channels             []string `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRequest) Reset()         { *m = BroadcastRequest{} }
func (m *BroadcastRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastRequest) ProtoMessage()    {}
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *BroadcastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRequest.Unmarshal(m, b)
}
func (m *BroadcastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRequest.Merge(m, src)
}
func (m *BroadcastRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastRequest.Size(m)
}
func (m *BroadcastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRequest proto.InternalMessageInfo

func (m *BroadcastRequest) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *BroadcastRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BroadcastResponse struct {
	Error                *Error           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *BroadcastResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BroadcastResponse) Reset()         { *m = BroadcastResponse{} }
func (m *BroadcastResponse) String() string { return proto.CompactTextString(m) }
func (*BroadcastResponse) ProtoMessage()    {}
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *BroadcastResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastResponse.Unmarshal(m, b)
}
func (m *BroadcastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastResponse.Marshal(b, m, deterministic)
}
func (m *BroadcastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastResponse.Merge(m, src)
}
func (m *BroadcastResponse) XXX_Size() int {
	return xxx_messageInfo_BroadcastResponse.Size(m)
}
func (m *BroadcastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastResponse proto.InternalMessageInfo

func (m *BroadcastResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BroadcastResponse) GetResult() *BroadcastResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type BroadcastResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastResult) Reset()         { *m = BroadcastResult{} }
func (m *BroadcastResult) String() string { return proto.CompactTextString(m) }
func (*BroadcastResult) ProtoMessage()    {}
func (*BroadcastResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *BroadcastResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastResult.Unmarshal(m, b)
}
func (m *BroadcastResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastResult.Marshal(b, m, deterministic)
}
func (m *BroadcastResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastResult.Merge(m, src)
}
func (m *BroadcastResult) XXX_Size() int {
	return xxx_messageInfo_BroadcastResult.Size(m)
}
func (m *BroadcastResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastResult.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastResult proto.InternalMessageInfo

type UnsubscribeRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

func (m *UnsubscribeRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *UnsubscribeRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type UnsubscribeResponse struct {
	Error                *Error             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *UnsubscribeResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UnsubscribeResponse) Reset()         { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()    {}
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *UnsubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeResponse.Unmarshal(m, b)
}
func (m *UnsubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeResponse.Marshal(b, m, deterministic)
}
func (m *UnsubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeResponse.Merge(m, src)
}
func (m *UnsubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeResponse.Size(m)
}
func (m *UnsubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeResponse proto.InternalMessageInfo

func (m *UnsubscribeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *UnsubscribeResponse) GetResult() *UnsubscribeResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type UnsubscribeResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeResult) Reset()         { *m = UnsubscribeResult{} }
func (m *UnsubscribeResult) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeResult) ProtoMessage()    {}
func (*UnsubscribeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *UnsubscribeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeResult.Unmarshal(m, b)
}
func (m *UnsubscribeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeResult.Marshal(b, m, deterministic)
}
func (m *UnsubscribeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeResult.Merge(m, src)
}
func (m *UnsubscribeResult) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeResult.Size(m)
}
func (m *UnsubscribeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeResult.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeResult proto.InternalMessageInfo

type DisconnectRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type DisconnectResponse struct {
	Error                *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *DisconnectResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func (m *DisconnectResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *DisconnectResponse) GetResult() *DisconnectResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type DisconnectResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResult) Reset()         { *m = DisconnectResult{} }
func (m *DisconnectResult) String() string { return proto.CompactTextString(m) }
func (*DisconnectResult) ProtoMessage()    {}
func (*DisconnectResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *DisconnectResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResult.Unmarshal(m, b)
}
func (m *DisconnectResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResult.Marshal(b, m, deterministic)
}
func (m *DisconnectResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResult.Merge(m, src)
}
func (m *DisconnectResult) XXX_Size() int {
	return xxx_messageInfo_DisconnectResult.Size(m)
}
func (m *DisconnectResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResult.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResult proto.InternalMessageInfo

type PresenceRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PresenceRequest) Reset()         { *m = PresenceRequest{} }
func (m *PresenceRequest) String() string { return proto.CompactTextString(m) }
func (*PresenceRequest) ProtoMessage()    {}
func (*PresenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *PresenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceRequest.Unmarshal(m, b)
}
func (m *PresenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceRequest.Marshal(b, m, deterministic)
}
func (m *PresenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceRequest.Merge(m, src)
}
func (m *PresenceRequest) XXX_Size() int {
	return xxx_messageInfo_PresenceRequest.Size(m)
}
func (m *PresenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceRequest proto.InternalMessageInfo

func (m *PresenceRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type PresenceResponse struct {
	Error                *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *PresenceResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PresenceResponse) Reset()         { *m = PresenceResponse{} }
func (m *PresenceResponse) String() string { return proto.CompactTextString(m) }
func (*PresenceResponse) ProtoMessage()    {}
func (*PresenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *PresenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceResponse.Unmarshal(m, b)
}
func (m *PresenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceResponse.Marshal(b, m, deterministic)
}
func (m *PresenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceResponse.Merge(m, src)
}
func (m *PresenceResponse) XXX_Size() int {
	return xxx_messageInfo_PresenceResponse.Size(m)
}
func (m *PresenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceResponse proto.InternalMessageInfo

func (m *PresenceResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PresenceResponse) GetResult() *PresenceResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type PresenceResult struct {
	Presence             map[string]*ClientInfo `protobuf:"bytes,1,rep,name=presence,proto3" json:"presence,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PresenceResult) Reset()         { *m = PresenceResult{} }
func (m *PresenceResult) String() string { return proto.CompactTextString(m) }
func (*PresenceResult) ProtoMessage()    {}
func (*PresenceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *PresenceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceResult.Unmarshal(m, b)
}
func (m *PresenceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceResult.Marshal(b, m, deterministic)
}
func (m *PresenceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceResult.Merge(m, src)
}
func (m *PresenceResult) XXX_Size() int {
	return xxx_messageInfo_PresenceResult.Size(m)
}
func (m *PresenceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceResult.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceResult proto.InternalMessageInfo

func (m *PresenceResult) GetPresence() map[string]*ClientInfo {
	if m != nil {
		return m.Presence
	}
	return nil
}

type PresenceStatsRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PresenceStatsRequest) Reset()         { *m = PresenceStatsRequest{} }
func (m *PresenceStatsRequest) String() string { return proto.CompactTextString(m) }
func (*PresenceStatsRequest) ProtoMessage()    {}
func (*PresenceStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *PresenceStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceStatsRequest.Unmarshal(m, b)
}
func (m *PresenceStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceStatsRequest.Marshal(b, m, deterministic)
}
func (m *PresenceStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceStatsRequest.Merge(m, src)
}
func (m *PresenceStatsRequest) XXX_Size() int {
	return xxx_messageInfo_PresenceStatsRequest.Size(m)
}
func (m *PresenceStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceStatsRequest proto.InternalMessageInfo

func (m *PresenceStatsRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type PresenceStatsResponse struct {
	Error                *Error               `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *PresenceStatsResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PresenceStatsResponse) Reset()         { *m = PresenceStatsResponse{} }
func (m *PresenceStatsResponse) String() string { return proto.CompactTextString(m) }
func (*PresenceStatsResponse) ProtoMessage()    {}
func (*PresenceStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *PresenceStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceStatsResponse.Unmarshal(m, b)
}
func (m *PresenceStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceStatsResponse.Marshal(b, m, deterministic)
}
func (m *PresenceStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceStatsResponse.Merge(m, src)
}
func (m *PresenceStatsResponse) XXX_Size() int {
	return xxx_messageInfo_PresenceStatsResponse.Size(m)
}
func (m *PresenceStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceStatsResponse proto.InternalMessageInfo

func (m *PresenceStatsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PresenceStatsResponse) GetResult() *PresenceStatsResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type PresenceStatsResult struct {
	NumClients           uint32   `protobuf:"varint,1,opt,name=num_clients,json=numClients,proto3" json:"num_clients,omitempty"`
	NumUsers             uint32   `protobuf:"varint,2,opt,name=num_users,json=numUsers,proto3" json:"num_users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PresenceStatsResult) Reset()         { *m = PresenceStatsResult{} }
func (m *PresenceStatsResult) String() string { return proto.CompactTextString(m) }
func (*PresenceStatsResult) ProtoMessage()    {}
func (*PresenceStatsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *PresenceStatsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceStatsResult.Unmarshal(m, b)
}
func (m *PresenceStatsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceStatsResult.Marshal(b, m, deterministic)
}
func (m *PresenceStatsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceStatsResult.Merge(m, src)
}
func (m *PresenceStatsResult) XXX_Size() int {
	return xxx_messageInfo_PresenceStatsResult.Size(m)
}
func (m *PresenceStatsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceStatsResult.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceStatsResult proto.InternalMessageInfo

func (m *PresenceStatsResult) GetNumClients() uint32 {
	if m != nil {
		return m.NumClients
	}
	return 0
}

func (m *PresenceStatsResult) GetNumUsers() uint32 {
	if m != nil {
		return m.NumUsers
	}
	return 0
}

type HistoryRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryRequest) Reset()         { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()    {}
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *HistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRequest.Unmarshal(m, b)
}
func (m *HistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRequest.Marshal(b, m, deterministic)
}
func (m *HistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRequest.Merge(m, src)
}
func (m *HistoryRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryRequest.Size(m)
}
func (m *HistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRequest proto.InternalMessageInfo

func (m *HistoryRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type HistoryResponse struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *HistoryResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HistoryResponse) Reset()         { *m = HistoryResponse{} }
func (m *HistoryResponse) String() string { return proto.CompactTextString(m) }
func (*HistoryResponse) ProtoMessage()    {}
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *HistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryResponse.Unmarshal(m, b)
}
func (m *HistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryResponse.Marshal(b, m, deterministic)
}
func (m *HistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryResponse.Merge(m, src)
}
func (m *HistoryResponse) XXX_Size() int {
	return xxx_messageInfo_HistoryResponse.Size(m)
}
func (m *HistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryResponse proto.InternalMessageInfo

func (m *HistoryResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *HistoryResponse) GetResult() *HistoryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type HistoryResult struct {
	Publications         []*Publication `protobuf:"bytes,1,rep,name=publications,proto3" json:"publications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HistoryResult) Reset()         { *m = HistoryResult{} }
func (m *HistoryResult) String() string { return proto.CompactTextString(m) }
func (*HistoryResult) ProtoMessage()    {}
func (*HistoryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *HistoryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryResult.Unmarshal(m, b)
}
func (m *HistoryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryResult.Marshal(b, m, deterministic)
}
func (m *HistoryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryResult.Merge(m, src)
}
func (m *HistoryResult) XXX_Size() int {
	return xxx_messageInfo_HistoryResult.Size(m)
}
func (m *HistoryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryResult.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryResult proto.InternalMessageInfo

func (m *HistoryResult) GetPublications() []*Publication {
	if m != nil {
		return m.Publications
	}
	return nil
}

type HistoryRemoveRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryRemoveRequest) Reset()         { *m = HistoryRemoveRequest{} }
func (m *HistoryRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryRemoveRequest) ProtoMessage()    {}
func (*HistoryRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *HistoryRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRemoveRequest.Unmarshal(m, b)
}
func (m *HistoryRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRemoveRequest.Marshal(b, m, deterministic)
}
func (m *HistoryRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRemoveRequest.Merge(m, src)
}
func (m *HistoryRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryRemoveRequest.Size(m)
}
func (m *HistoryRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRemoveRequest proto.InternalMessageInfo

func (m *HistoryRemoveRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type HistoryRemoveResponse struct {
	Error                *Error               `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *HistoryRemoveResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HistoryRemoveResponse) Reset()         { *m = HistoryRemoveResponse{} }
func (m *HistoryRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*HistoryRemoveResponse) ProtoMessage()    {}
func (*HistoryRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *HistoryRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRemoveResponse.Unmarshal(m, b)
}
func (m *HistoryRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRemoveResponse.Marshal(b, m, deterministic)
}
func (m *HistoryRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRemoveResponse.Merge(m, src)
}
func (m *HistoryRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_HistoryRemoveResponse.Size(m)
}
func (m *HistoryRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRemoveResponse proto.InternalMessageInfo

func (m *HistoryRemoveResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *HistoryRemoveResponse) GetResult() *HistoryRemoveResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type HistoryRemoveResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryRemoveResult) Reset()         { *m = HistoryRemoveResult{} }
func (m *HistoryRemoveResult) String() string { return proto.CompactTextString(m) }
func (*HistoryRemoveResult) ProtoMessage()    {}
func (*HistoryRemoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}

func (m *HistoryRemoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRemoveResult.Unmarshal(m, b)
}
func (m *HistoryRemoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRemoveResult.Marshal(b, m, deterministic)
}
func (m *HistoryRemoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRemoveResult.Merge(m, src)
}
func (m *HistoryRemoveResult) XXX_Size() int {
	return xxx_messageInfo_HistoryRemoveResult.Size(m)
}
func (m *HistoryRemoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRemoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRemoveResult proto.InternalMessageInfo

type ChannelsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelsRequest) Reset()         { *m = ChannelsRequest{} }
func (m *ChannelsRequest) String() string { return proto.CompactTextString(m) }
func (*ChannelsRequest) ProtoMessage()    {}
func (*ChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}

func (m *ChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelsRequest.Unmarshal(m, b)
}
func (m *ChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelsRequest.Marshal(b, m, deterministic)
}
func (m *ChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelsRequest.Merge(m, src)
}
func (m *ChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_ChannelsRequest.Size(m)
}
func (m *ChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelsRequest proto.InternalMessageInfo

type ChannelsResponse struct {
	Error                *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *ChannelsResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChannelsResponse) Reset()         { *m = ChannelsResponse{} }
func (m *ChannelsResponse) String() string { return proto.CompactTextString(m) }
func (*ChannelsResponse) ProtoMessage()    {}
func (*ChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}

func (m *ChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelsResponse.Unmarshal(m, b)
}
func (m *ChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelsResponse.Marshal(b, m, deterministic)
}
func (m *ChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelsResponse.Merge(m, src)
}
func (m *ChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_ChannelsResponse.Size(m)
}
func (m *ChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelsResponse proto.InternalMessageInfo

func (m *ChannelsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ChannelsResponse) GetResult() *ChannelsResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ChannelsResult struct {
	Channels             []string `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelsResult) Reset()         { *m = ChannelsResult{} }
func (m *ChannelsResult) String() string { return proto.CompactTextString(m) }
func (*ChannelsResult) ProtoMessage()    {}
func (*ChannelsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{31}
}

func (m *ChannelsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelsResult.Unmarshal(m, b)
}
func (m *ChannelsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelsResult.Marshal(b, m, deterministic)
}
func (m *ChannelsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelsResult.Merge(m, src)
}
func (m *ChannelsResult) XXX_Size() int {
	return xxx_messageInfo_ChannelsResult.Size(m)
}
func (m *ChannelsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelsResult.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelsResult proto.InternalMessageInfo

func (m *ChannelsResult) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{32}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoResponse struct {
	Error                *Error      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               *InfoResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{33}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *InfoResponse) GetResult() *InfoResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type InfoResult struct {
	Nodes                []*NodeResult `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InfoResult) Reset()         { *m = InfoResult{} }
func (m *InfoResult) String() string { return proto.CompactTextString(m) }
func (*InfoResult) ProtoMessage()    {}
func (*InfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{34}
}

func (m *InfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResult.Unmarshal(m, b)
}
func (m *InfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResult.Marshal(b, m, deterministic)
}
func (m *InfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResult.Merge(m, src)
}
func (m *InfoResult) XXX_Size() int {
	return xxx_messageInfo_InfoResult.Size(m)
}
func (m *InfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResult proto.InternalMessageInfo

func (m *InfoResult) GetNodes() []*NodeResult {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeResult struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	NumClients           uint32   `protobuf:"varint,4,opt,name=num_clients,json=numClients,proto3" json:"num_clients,omitempty"`
	NumUsers             uint32   `protobuf:"varint,5,opt,name=num_users,json=numUsers,proto3" json:"num_users,omitempty"`
	NumChannels          uint32   `protobuf:"varint,6,opt,name=num_channels,json=numChannels,proto3" json:"num_channels,omitempty"`
	Uptime               uint32   `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Metrics              *Metrics `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeResult) Reset()         { *m = NodeResult{} }
func (m *NodeResult) String() string { return proto.CompactTextString(m) }
func (*NodeResult) ProtoMessage()    {}
func (*NodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{35}
}

func (m *NodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeResult.Unmarshal(m, b)
}
func (m *NodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeResult.Marshal(b, m, deterministic)
}
func (m *NodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResult.Merge(m, src)
}
func (m *NodeResult) XXX_Size() int {
	return xxx_messageInfo_NodeResult.Size(m)
}
func (m *NodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResult proto.InternalMessageInfo

func (m *NodeResult) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *NodeResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeResult) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeResult) GetNumClients() uint32 {
	if m != nil {
		return m.NumClients
	}
	return 0
}

func (m *NodeResult) GetNumUsers() uint32 {
	if m != nil {
		return m.NumUsers
	}
	return 0
}

func (m *NodeResult) GetNumChannels() uint32 {
	if m != nil {
		return m.NumChannels
	}
	return 0
}

func (m *NodeResult) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *NodeResult) GetMetrics() *Metrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metrics struct {
	Interval             float64            `protobuf:"fixed64,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Items                map[string]float64 `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{36}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetInterval() float64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Metrics) GetItems() map[string]float64 {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.MethodType", MethodType_name, MethodType_value)
	proto.RegisterType((*ClientInfo)(nil), "api.ClientInfo")
	proto.RegisterType((*Publication)(nil), "api.Publication")
	proto.RegisterType((*Error)(nil), "api.Error")
	proto.RegisterType((*Command)(nil), "api.Command")
	proto.RegisterType((*Reply)(nil), "api.Reply")
	proto.RegisterType((*PublishRequest)(nil), "api.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "api.PublishResponse")
	proto.RegisterType((*PublishResult)(nil), "api.PublishResult")
	proto.RegisterType((*BroadcastRequest)(nil), "api.BroadcastRequest")
	proto.RegisterType((*BroadcastResponse)(nil), "api.BroadcastResponse")
	proto.RegisterType((*BroadcastResult)(nil), "api.BroadcastResult")
	proto.RegisterType((*UnsubscribeRequest)(nil), "api.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeResponse)(nil), "api.UnsubscribeResponse")
	proto.RegisterType((*UnsubscribeResult)(nil), "api.UnsubscribeResult")
	proto.RegisterType((*DisconnectRequest)(nil), "api.DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "api.DisconnectResponse")
	proto.RegisterType((*DisconnectResult)(nil), "api.DisconnectResult")
	proto.RegisterType((*PresenceRequest)(nil), "api.PresenceRequest")
	proto.RegisterType((*PresenceResponse)(nil), "api.PresenceResponse")
	proto.RegisterType((*PresenceResult)(nil), "api.PresenceResult")
	proto.RegisterMapType((map[string]*ClientInfo)(nil), "api.PresenceResult.PresenceEntry")
	proto.RegisterType((*PresenceStatsRequest)(nil), "api.PresenceStatsRequest")
	proto.RegisterType((*PresenceStatsResponse)(nil), "api.PresenceStatsResponse")
	proto.RegisterType((*PresenceStatsResult)(nil), "api.PresenceStatsResult")
	proto.RegisterType((*HistoryRequest)(nil), "api.HistoryRequest")
	proto.RegisterType((*HistoryResponse)(nil), "api.HistoryResponse")
	proto.RegisterType((*HistoryResult)(nil), "api.HistoryResult")
	proto.RegisterType((*HistoryRemoveRequest)(nil), "api.HistoryRemoveRequest")
	proto.RegisterType((*HistoryRemoveResponse)(nil), "api.HistoryRemoveResponse")
	proto.RegisterType((*HistoryRemoveResult)(nil), "api.HistoryRemoveResult")
	proto.RegisterType((*ChannelsRequest)(nil), "api.ChannelsRequest")
	proto.RegisterType((*ChannelsResponse)(nil), "api.ChannelsResponse")
	proto.RegisterType((*ChannelsResult)(nil), "api.ChannelsResult")
	proto.RegisterType((*InfoRequest)(nil), "api.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "api.InfoResponse")
	proto.RegisterType((*InfoResult)(nil), "api.InfoResult")
	proto.RegisterType((*NodeResult)(nil), "api.NodeResult")
	proto.RegisterType((*Metrics)(nil), "api.Metrics")
	proto.RegisterMapType((map[string]float64)(nil), "api.Metrics.ItemsEntry")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x4f, 0xe3, 0x46,
	0x14, 0xc6, 0x21, 0x21, 0xc9, 0xc9, 0xcd, 0x4c, 0x02, 0xa4, 0xf4, 0xa1, 0xac, 0xab, 0x16, 0xc4,
	0x2e, 0x68, 0xc5, 0xb6, 0xab, 0x6d, 0xd5, 0x8b, 0x48, 0x70, 0x45, 0x24, 0x36, 0x50, 0x3b, 0x54,
	0xdd, 0xbe, 0x44, 0x26, 0x19, 0xc0, 0x22, 0xb6, 0x53, 0x8f, 0x8d, 0x94, 0x3f, 0xd1, 0x7f, 0xd0,
	0xb7, 0xfe, 0xbd, 0xbe, 0xf7, 0xb1, 0x9a, 0x9b, 0x6f, 0xf1, 0x2e, 0x91, 0x78, 0xf3, 0x99, 0xef,
	0xcc, 0xe7, 0x6f, 0x8e, 0xe7, 0x5c, 0x0c, 0x55, 0x6b, 0x6e, 0x1f, 0xcf, 0x7d, 0x2f, 0xf0, 0xd0,
	0xba, 0x35, 0xb7, 0x35, 0x1f, 0xa0, 0x3f, 0xb3, 0xb1, 0x1b, 0x0c, 0xdc, 0x5b, 0x0f, 0x21, 0x28,
	0x86, 0x04, 0xfb, 0x5d, 0x65, 0x4f, 0x39, 0xa8, 0x1a, 0xec, 0x19, 0x6d, 0xc3, 0xc6, 0x84, 0x79,
	0x74, 0x0b, 0x6c, 0x55, 0x58, 0xe8, 0x73, 0xa8, 0x4e, 0x3c, 0xd7, 0x1d, 0xdb, 0xee, 0xad, 0xd7,
	0x5d, 0xdf, 0x53, 0x0e, 0xea, 0x46, 0x85, 0x2e, 0x30, 0x22, 0x0a, 0xde, 0x5b, 0x02, 0x2c, 0x0a,
	0xf0, 0xde, 0x62, 0xa0, 0xf6, 0x3b, 0xd4, 0xae, 0xc2, 0x9b, 0x99, 0x3d, 0xb1, 0x02, 0xdb, 0x73,
	0x91, 0x0a, 0xeb, 0xa1, 0x3d, 0x15, 0xef, 0xa4, 0x8f, 0x54, 0xc6, 0xd4, 0x0a, 0x2c, 0xf6, 0xc2,
	0xba, 0xc1, 0x9e, 0xd1, 0x97, 0x50, 0x8c, 0xde, 0x54, 0x3b, 0x69, 0x1d, 0xd3, 0x73, 0xc4, 0xca,
	0x0d, 0x06, 0x6a, 0xdf, 0x42, 0x49, 0xf7, 0x7d, 0xcf, 0xa7, 0x0c, 0x13, 0x6f, 0x8a, 0x19, 0x69,
	0xc3, 0x60, 0xcf, 0xa8, 0x0b, 0x65, 0x07, 0x13, 0x62, 0xdd, 0x61, 0x71, 0x12, 0x69, 0x6a, 0x7f,
	0x40, 0xb9, 0xef, 0x39, 0x8e, 0xe5, 0x4e, 0x51, 0x13, 0x0a, 0x42, 0x4b, 0xc3, 0x28, 0xd8, 0x53,
	0xb4, 0x0f, 0x1b, 0x0e, 0x0e, 0xee, 0xbd, 0x29, 0xdb, 0xd3, 0x14, 0x2f, 0x7e, 0xcf, 0x96, 0x46,
	0x8b, 0x39, 0x36, 0x04, 0x4c, 0xc3, 0x34, 0xb7, 0x7c, 0xcb, 0x21, 0x22, 0x16, 0xc2, 0xd2, 0x7e,
	0x85, 0x92, 0x81, 0xe7, 0xb3, 0xc5, 0x12, 0xf3, 0x1e, 0x94, 0x30, 0xd5, 0xca, 0x88, 0x6b, 0x27,
	0xc0, 0x88, 0x99, 0x7a, 0x83, 0x03, 0x94, 0xd2, 0xc7, 0x24, 0x9c, 0x05, 0x92, 0x92, 0x5b, 0xda,
	0x4f, 0xd0, 0x64, 0xf1, 0x23, 0xf7, 0x06, 0xfe, 0x33, 0xc4, 0x24, 0xa0, 0x47, 0xa3, 0xd1, 0x75,
	0xf1, 0x4c, 0x84, 0x51, 0x9a, 0x79, 0xa1, 0xd4, 0xc6, 0xd0, 0x8a, 0xf6, 0x93, 0xb9, 0xe7, 0x12,
	0x1c, 0x8b, 0x51, 0x3e, 0x26, 0xe6, 0x30, 0x12, 0xc3, 0xf5, 0x22, 0xe6, 0x12, 0xf3, 0x84, 0xb3,
	0x20, 0x12, 0xd8, 0x82, 0x46, 0x0a, 0xd0, 0x7a, 0xa0, 0xf6, 0x7c, 0xcf, 0x9a, 0x4e, 0x2c, 0x12,
	0x48, 0xcd, 0xbb, 0x50, 0x11, 0x22, 0x49, 0x57, 0xd9, 0x5b, 0x3f, 0xa8, 0x1a, 0x91, 0x9d, 0xab,
	0x7a, 0x02, 0x9b, 0x09, 0x8e, 0x95, 0x75, 0xbf, 0xca, 0xe8, 0xee, 0x30, 0x97, 0x24, 0x53, 0x52,
	0xf9, 0x26, 0xb4, 0x32, 0x90, 0xd6, 0x03, 0x74, 0xed, 0x92, 0xf0, 0x86, 0x4c, 0x7c, 0xfb, 0x06,
	0xaf, 0x14, 0x71, 0x96, 0x43, 0x85, 0x38, 0x87, 0xb4, 0x3b, 0x68, 0xa7, 0x38, 0x56, 0x56, 0x7f,
	0x9c, 0x51, 0xbf, 0xcd, 0x5c, 0xd2, 0x5c, 0x49, 0xfd, 0x6d, 0xd8, 0x5c, 0x02, 0xb5, 0x7d, 0xd8,
	0x3c, 0xb3, 0x09, 0xcd, 0x4d, 0x3c, 0x89, 0xc2, 0x9f, 0x93, 0xea, 0x1a, 0x06, 0x94, 0x74, 0x5c,
	0x59, 0xe5, 0x51, 0x46, 0xe5, 0x16, 0x73, 0x49, 0x51, 0x25, 0x45, 0x22, 0x50, 0xb3, 0x98, 0xf6,
	0x12, 0x5a, 0x57, 0x3e, 0x26, 0xd8, 0x9d, 0x3c, 0x1d, 0x62, 0xcd, 0x02, 0x35, 0x76, 0x5e, 0x59,
	0xe5, 0xcb, 0x8c, 0xca, 0x36, 0xbf, 0xc1, 0x31, 0x51, 0x52, 0xe3, 0xdf, 0x0a, 0x34, 0xd3, 0x10,
	0xfa, 0x11, 0x2a, 0x73, 0xb1, 0xc2, 0x2e, 0x6c, 0xed, 0xe4, 0x45, 0x0e, 0x43, 0x64, 0xea, 0x6e,
	0xe0, 0x2f, 0x8c, 0x68, 0xcb, 0xee, 0x05, 0x34, 0x52, 0x10, 0xad, 0x7b, 0x0f, 0x78, 0x21, 0xeb,
	0xde, 0x03, 0x5e, 0xa0, 0xaf, 0xa0, 0xf4, 0x68, 0xcd, 0x42, 0x2c, 0x04, 0x2e, 0x15, 0x39, 0x8e,
	0x7e, 0x5f, 0x78, 0xa7, 0x68, 0xaf, 0xa1, 0x23, 0xd9, 0xcc, 0xc0, 0x0a, 0xc8, 0xd3, 0x41, 0x7b,
	0x80, 0xad, 0xcc, 0x8e, 0x95, 0x23, 0xf7, 0x3a, 0x13, 0xb9, 0x6e, 0xea, 0xdc, 0x92, 0x2d, 0x19,
	0x3e, 0x13, 0xda, 0x39, 0x30, 0xfa, 0x02, 0x6a, 0x6e, 0xe8, 0x8c, 0x79, 0x07, 0x21, 0xa2, 0x18,
	0x82, 0x1b, 0x3a, 0xfc, 0x90, 0x84, 0xf6, 0x0d, 0xea, 0x40, 0x6f, 0x23, 0x61, 0x2f, 0x6b, 0x18,
	0x15, 0x37, 0x74, 0xae, 0xa9, 0xad, 0x1d, 0x42, 0xf3, 0xdc, 0x26, 0x81, 0xe7, 0x2f, 0x9e, 0x3e,
	0xed, 0x18, 0x5a, 0x91, 0xef, 0x33, 0x6b, 0x5c, 0xcc, 0x93, 0x3c, 0xa1, 0x0e, 0x8d, 0x14, 0x80,
	0xbe, 0x81, 0xfa, 0x3c, 0xee, 0x6a, 0x44, 0x5c, 0x11, 0x35, 0x2e, 0x93, 0x1c, 0x30, 0x52, 0x5e,
	0xf4, 0x3b, 0x46, 0x34, 0x8e, 0xf7, 0x88, 0x57, 0xfa, 0x8e, 0x99, 0x1d, 0xcf, 0xfc, 0x8e, 0x59,
	0xb6, 0xe4, 0x29, 0xb7, 0xa0, 0x9d, 0x03, 0xd3, 0x32, 0xd9, 0x17, 0xb5, 0x5a, 0x08, 0xa6, 0x39,
	0x19, 0x2f, 0x3d, 0x33, 0x27, 0x13, 0x44, 0x49, 0x31, 0xaf, 0xa0, 0x99, 0x46, 0x3e, 0xd5, 0x43,
	0xb4, 0x06, 0xd4, 0x58, 0xd2, 0x08, 0x7d, 0x1f, 0xa0, 0xce, 0xcd, 0x95, 0xb5, 0xed, 0x67, 0xb4,
	0xf1, 0x74, 0x14, 0x24, 0x49, 0x5d, 0x6f, 0x00, 0xe2, 0x55, 0x9a, 0xc4, 0xae, 0x37, 0xc5, 0xf2,
	0x02, 0xf0, 0x5d, 0x43, 0x6f, 0x2a, 0x43, 0xcb, 0x51, 0xed, 0x5f, 0x05, 0x20, 0x5e, 0xcd, 0x1f,
	0x82, 0x5c, 0xcb, 0x91, 0xb3, 0x0a, 0x7b, 0xa6, 0xb7, 0xe2, 0x11, 0xfb, 0xc4, 0xf6, 0x5c, 0x36,
	0x12, 0x54, 0x0d, 0x69, 0x66, 0x33, 0xab, 0xf8, 0xe9, 0xcc, 0x2a, 0xa5, 0x33, 0x0b, 0xbd, 0x80,
	0x3a, 0xdb, 0x2d, 0x63, 0xb9, 0xc1, 0x70, 0xca, 0x28, 0x03, 0x4e, 0x87, 0x91, 0x70, 0x1e, 0xd8,
	0x0e, 0xee, 0x96, 0x19, 0x28, 0x2c, 0xf4, 0x35, 0x9d, 0xaa, 0x02, 0xdf, 0x9e, 0x90, 0x6e, 0x85,
	0x85, 0xa9, 0x2e, 0x27, 0x24, 0xba, 0x66, 0x48, 0x50, 0xfb, 0x4b, 0x81, 0xb2, 0x58, 0xa4, 0x9f,
	0xcd, 0x76, 0x03, 0xec, 0x3f, 0x5a, 0xfc, 0x76, 0x2b, 0x46, 0x64, 0xa3, 0x23, 0x28, 0xd9, 0x01,
	0x76, 0x68, 0xf6, 0xd3, 0xf0, 0xed, 0x24, 0xd9, 0x8e, 0x07, 0x14, 0xe1, 0x85, 0x95, 0x7b, 0xed,
	0xbe, 0x03, 0x88, 0x17, 0x73, 0x4a, 0x6a, 0x27, 0x59, 0x52, 0x95, 0x44, 0x05, 0x3d, 0xfc, 0x47,
	0x01, 0x88, 0xe7, 0x38, 0x54, 0x83, 0xf2, 0xd5, 0x75, 0xef, 0x62, 0x60, 0x9e, 0xab, 0x6b, 0xa8,
	0x01, 0xd5, 0x9e, 0x71, 0x79, 0x7a, 0xd6, 0x3f, 0x35, 0x47, 0xaa, 0x82, 0x5a, 0x50, 0xbb, 0x1e,
	0x9a, 0xd7, 0x3d, 0xb3, 0x6f, 0x0c, 0x7a, 0xba, 0x5a, 0x40, 0x4d, 0x80, 0xb3, 0x81, 0xd9, 0xbf,
	0x1c, 0x0e, 0xf5, 0xfe, 0x48, 0x5d, 0x47, 0x75, 0xa8, 0x5c, 0x19, 0xba, 0xa9, 0x0f, 0xfb, 0xba,
	0x5a, 0x44, 0x08, 0x9a, 0xd2, 0x1a, 0x9b, 0xa3, 0xd3, 0x91, 0xa9, 0x96, 0x28, 0xfd, 0xf9, 0xc0,
	0x1c, 0x5d, 0x1a, 0x1f, 0xd4, 0x0d, 0xea, 0x20, 0x8c, 0xb1, 0xa1, 0xbf, 0xbf, 0xfc, 0x4d, 0x57,
	0xcb, 0x94, 0xa2, 0x7f, 0x7e, 0x3a, 0x1c, 0xea, 0x17, 0xa6, 0x5a, 0x41, 0x15, 0x28, 0x0e, 0x86,
	0xbf, 0x5c, 0xaa, 0xd5, 0x93, 0xff, 0x8a, 0x00, 0x7d, 0xec, 0x06, 0xbe, 0x7d, 0x1b, 0xde, 0x79,
	0xe8, 0x2d, 0x94, 0xc5, 0x68, 0x85, 0xda, 0xe9, 0x09, 0x8c, 0x5d, 0xf3, 0xdd, 0x4e, 0x66, 0x2c,
	0x63, 0x97, 0x5d, 0x5b, 0x43, 0x3f, 0x40, 0x35, 0x1a, 0x6c, 0xd0, 0x56, 0x76, 0x06, 0xe2, 0x7b,
	0xb7, 0x97, 0x46, 0x23, 0xb9, 0xbb, 0x07, 0xb5, 0xc4, 0x58, 0x81, 0x76, 0x96, 0xa7, 0x10, 0xce,
	0xd0, 0xcd, 0x19, 0x4f, 0x24, 0xc7, 0xcf, 0x00, 0x71, 0xd7, 0x47, 0xdb, 0x4b, 0x23, 0x02, 0x67,
	0xd8, 0x59, 0x1e, 0x1d, 0x24, 0xc1, 0x77, 0x50, 0x91, 0x3d, 0x05, 0x75, 0x32, 0x9d, 0x97, 0x6f,
	0xde, 0xca, 0xf6, 0x63, 0xb9, 0xf5, 0x3c, 0xee, 0xbd, 0xac, 0x1d, 0xa1, 0xcf, 0xf2, 0x3a, 0x18,
	0x27, 0xd9, 0xcd, 0x6d, 0x6e, 0x92, 0xe9, 0x2d, 0x94, 0x45, 0x41, 0x14, 0xf1, 0x4f, 0x77, 0x24,
	0x11, 0xff, 0x4c, 0xeb, 0xe1, 0x0a, 0x52, 0x85, 0x54, 0x28, 0xc8, 0xab, 0xfd, 0x42, 0x41, 0x6e,
	0x91, 0xe7, 0x61, 0x88, 0x92, 0xb2, 0x93, 0x29, 0x97, 0xc9, 0x30, 0x64, 0xab, 0xb1, 0xb6, 0x86,
	0x8e, 0xa0, 0xc8, 0xfe, 0xce, 0xd4, 0x44, 0x25, 0xe3, 0x5b, 0x36, 0x93, 0xb5, 0x4d, 0xb8, 0xdf,
	0x6c, 0xb0, 0xff, 0xc4, 0x37, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xe5, 0xe0, 0xa1, 0x34,
	0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CentrifugoClient is the client API for Centrifugo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CentrifugoClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	Presence(ctx context.Context, in *PresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error)
	PresenceStats(ctx context.Context, in *PresenceStatsRequest, opts ...grpc.CallOption) (*PresenceStatsResponse, error)
	History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	HistoryRemove(ctx context.Context, in *HistoryRemoveRequest, opts ...grpc.CallOption) (*HistoryRemoveResponse, error)
	Channels(ctx context.Context, in *ChannelsRequest, opts ...grpc.CallOption) (*ChannelsResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type centrifugoClient struct {
	cc *grpc.ClientConn
}

func NewCentrifugoClient(cc *grpc.ClientConn) CentrifugoClient {
	return &centrifugoClient{cc}
}

func (c *centrifugoClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) Presence(ctx context.Context, in *PresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error) {
	out := new(PresenceResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/Presence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) PresenceStats(ctx context.Context, in *PresenceStatsRequest, opts ...grpc.CallOption) (*PresenceStatsResponse, error) {
	out := new(PresenceStatsResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/PresenceStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/History", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) HistoryRemove(ctx context.Context, in *HistoryRemoveRequest, opts ...grpc.CallOption) (*HistoryRemoveResponse, error) {
	out := new(HistoryRemoveResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/HistoryRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) Channels(ctx context.Context, in *ChannelsRequest, opts ...grpc.CallOption) (*ChannelsResponse, error) {
	out := new(ChannelsResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/Channels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centrifugoClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/api.Centrifugo/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentrifugoServer is the server API for Centrifugo service.
type CentrifugoServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	Presence(context.Context, *PresenceRequest) (*PresenceResponse, error)
	PresenceStats(context.Context, *PresenceStatsRequest) (*PresenceStatsResponse, error)
	History(context.Context, *HistoryRequest) (*HistoryResponse, error)
	HistoryRemove(context.Context, *HistoryRemoveRequest) (*HistoryRemoveResponse, error)
	Channels(context.Context, *ChannelsRequest) (*ChannelsResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterCentrifugoServer(s *grpc.Server, srv CentrifugoServer) {
	s.RegisterService(&_Centrifugo_serviceDesc, srv)
}

func _Centrifugo_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_Presence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).Presence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/Presence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).Presence(ctx, req.(*PresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_PresenceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresenceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).PresenceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/PresenceStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).PresenceStats(ctx, req.(*PresenceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/History",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).History(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_HistoryRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).HistoryRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/HistoryRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).HistoryRemove(ctx, req.(*HistoryRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_Channels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).Channels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/Channels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).Channels(ctx, req.(*ChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Centrifugo_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentrifugoServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Centrifugo/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentrifugoServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Centrifugo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Centrifugo",
	HandlerType: (*CentrifugoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Centrifugo_Publish_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _Centrifugo_Broadcast_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _Centrifugo_Unsubscribe_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Centrifugo_Disconnect_Handler,
		},
		{
			MethodName: "Presence",
			Handler:    _Centrifugo_Presence_Handler,
		},
		{
			MethodName: "PresenceStats",
			Handler:    _Centrifugo_PresenceStats_Handler,
		},
		{
			MethodName: "History",
			Handler:    _Centrifugo_History_Handler,
		},
		{
			MethodName: "HistoryRemove",
			Handler:    _Centrifugo_HistoryRemove_Handler,
		},
		{
			MethodName: "Channels",
			Handler:    _Centrifugo_Channels_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Centrifugo_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
